---
title: "CS_Assigment_01"
author: "Anna"
date: "2024-02-27"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(ggplot2)

set.seed(42)

# function to fit linear model and to get r-squared
mc_simulation <- function(n, p) {
  X <- matrix(rnorm(n * p), nrow = n, ncol = p)
  beta <- rep(1, p)
  e <- rnorm(n, mean = 0, sd = 5)
  y <- X %*% beta + e 
  fit <- lm(y ~ X)
  R2 <- summary(fit)$r.squared
  return(R2)
}

# setting the number of simulations, observations and predictors
simulations <- 100
observations <- seq(5, 100, by = 5)
predictors <- seq(1, 20, by = 1)

results <- expand.grid(observations = observations, predictors = predictors)


for (i in simulations) {
  results$r.squared <- mapply(mc_simulation, results$observations, results$predictors)
}

# Boxplot of R-squared values grouped by the number of predictors
ggplot(results, aes(x = factor(predictors), y = r.squared)) +
  geom_boxplot() +
  labs(title = "Distribution of R-squared in relation to Number of Predictors",
       x = "Number of Predictors",
       y = "R-squared") +
  theme_minimal()
ggsave('point1_boxplot.png')

# Heatmap of R-squared in relation to observations and predictors 
ggplot(results, aes(x = factor(predictors), y = factor(observations), fill = r.squared)) +
  geom_tile() + 
  scale_fill_gradient(low = "blue", high = "red", name = "R-squared") +
  labs(title = "Heatmap of R-squared in relation to Number of Predictors and Observations",
       x = "No of Predictors",
       y = "No of Observations") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave('point1_heatmap.png')

```